# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MCIns' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'MBProgressHUD'
  pod 'YPImagePicker','~> 3.4.0'
  pod 'JXPhotoBrowser', '~> 1.5.0'
  pod 'SDWebImage'
  pod 'IGListKit'
  pod 'TwicketSegmentedControl','~> 0.1.1'
  pod 'GooglePlaces'
  pod 'PullToRefresher'
  # Pods for MCIns

end
